### ISSUE TITLE
Support Hash Lookup Type

### ISSUE THREAD

**Issue by jjulien** [jjulien/hiera-regex#2]
Currently only the priority lookup type is supported, we should add hash lookup types as well to allow recursive lookups through the hierarchy.

More info on lookup types can be found here
http://docs.puppetlabs.com/hiera/1/custom_backends.html#handling-lookup-types

**Comment by cleung2010** [comment]
I am using a module called puppet-consul, and there is a class variable named config_hash: https://github.com/solarkennedy/puppet-consul/blob/master/manifests/init.pp

I tried using hiera-regex to fill a key-value pair in that hash like so:

```yaml
---
 - 'localdc[0-9]{1}'
    consul::config_hash:
        datacenter: 'dc1'
```

However, the `datacenter` value does not seem to appear anywhere after the puppet run.

**Comment by cleung2010** [comment]
It might be also worth mentioning that I have config_hash defined in my default.pp (or site.pp). I only want certain KV pairs from configh_hash to be in hiera so it might be because it is, as you pointed out, not doing the merge.

**Comment by jjulien** [comment]
Hey @cleung2010 ,
If you are passing in config_hash then hiera will never look that up or attempt to merge it.  Sounds like you don't need hiera hash merging but puppet hash merging.  If you have the puppetlabs-stdlib module installed, it supports this.  Your class would need to do something like this.

```
class consul($config_hash) {
  $merged_config = merge($config_hash, hiera('consul::config_hash'))
}
```
Since you don't control the consul class, you could probably just do the merge in site.pp instead.
```
class {'consul':
    config_hash => merge({'somekey' => 'somevalue'}, hiera('consul::config_hash'))
}
```

**Comment by cleung2010** [comment]
What if config_hash is in both common.yaml and hostname.regex, then would that be hiera hash merging? I am planning to remove config_hash from my site.pp and have the common KV values of config_hash in common.yaml

**Comment by jjulien** [comment]
@cleung2010 ,
Yes, that would be hiera hash merging and what this feature would enable.  I do not have an ETA when it will be implemented.

**Comment by cleung2010** [comment]
Alright, mind if I fork to try to work on it and then send you a pull request?

**Comment by jjulien** [comment]
Not at all, thanks!
