### ISSUE TITLE
Interpolation inside hashes does not work

### ISSUE THREAD

**Issue by cleung2010** [jjulien/hiera-regex#3]
If I interpolate variables inside a hash it does not work.

For example, using the puppet-consul module, I can set the `bind_addr` key inside `consul::config_hash` with properly interpolated string in common.yaml

```yaml
---
consul::config_hash: 
  bind_addr: '%{::ipaddress_eth1}'
```

which yields

```
{
  "bind_addr": "192.168.101.1"
}
```

However, when I declare it in hostname.regex

```yaml
---
 - 'localdc[0-9]{1}':
    consul::config_hash: 
      bind_addr: "%{::ipaddress_eth1}"
```

It simply comes back as a non-interpolated string:

```
{
  "bind_addr": "%{::ipaddress_eth1}"
}
```

**Comment by jjulien** [comment]
@cleung2010 ,
Thanks for reporting this, it is now fixed in version 0.2.1.
